services:
  time:
    image: mcp/time
    
  filesystem:
    image: mcp/filesystem
    command: /workspace
    volumes:
      - .:/workspace
      
  sqlite:
    image: mcp/sqlite
    
  puppeteer:
    image: mcp/puppeteer
    environment:
      - DOCKER_CONTAINER=true
      
  github:
    image: mcp/github
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_TOKEN}
      
  postgres:
    image: mcp/postgres
    # Add your PostgreSQL connection string here
    # command: postgresql://user:password@host:port/database
    
  memory:
    image: mcp/memory
    volumes:
      - ./mcp-data:/app/data
      
  fetch:
    image: mcp/fetch
    
  git:
    image: mcp/git
    volumes:
      - .:/repo
    command: /repo
    
  stagehand:
    build: ./mcp-server-browserbase/stagehand
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BROWSERBASE_API_KEY=bb_live_audK__wfBIXmt1LU1PAy-O4QVEk
      - BROWSERBASE_PROJECT_ID=770de61f-ca88-4e5a-8ba9-b888338f08f7
    volumes:
      - ./mcp-server-browserbase/stagehand:/app 